// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdV51yuMTAjck7Y34w1Lw8S5SRvQsbqms',
    appId: '1:287989107795:web:29d2b580ab8c71d1b1caa6',
    messagingSenderId: '287989107795',
    projectId: 'transitease-6b58a',
    authDomain: 'transitease-6b58a.firebaseapp.com',
    storageBucket: 'transitease-6b58a.appspot.com',
    measurementId: 'G-LHJZKF2CFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPPHQYWEeCyIxcUfqoAqCDVpLj_0Fvgls',
    appId: '1:287989107795:android:9752f26b2f9e69edb1caa6',
    messagingSenderId: '287989107795',
    projectId: 'transitease-6b58a',
    storageBucket: 'transitease-6b58a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoVLEoyBYyOMolBFejSgAyjtyQPSsoNk0',
    appId: '1:287989107795:ios:db1333a35e3c2bacb1caa6',
    messagingSenderId: '287989107795',
    projectId: 'transitease-6b58a',
    storageBucket: 'transitease-6b58a.appspot.com',
    iosClientId: '287989107795-3b5ne3coqejicbgdiuc64u7p3h4lu7h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.transitease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoVLEoyBYyOMolBFejSgAyjtyQPSsoNk0',
    appId: '1:287989107795:ios:db1333a35e3c2bacb1caa6',
    messagingSenderId: '287989107795',
    projectId: 'transitease-6b58a',
    storageBucket: 'transitease-6b58a.appspot.com',
    iosClientId: '287989107795-3b5ne3coqejicbgdiuc64u7p3h4lu7h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.transitease',
  );
}
